# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.oldButton = QtWidgets.QPushButton(Form)
        self.oldButton.setGeometry(QtCore.QRect(40, 50, 331, 61))
        self.oldButton.setObjectName("oldButton")
        self.newButton = QtWidgets.QPushButton(Form)
        self.newButton.setGeometry(QtCore.QRect(40, 130, 331, 61))
        self.newButton.setObjectName("newButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Что-то меняем"))
        self.oldButton.setText(_translate("Form", "Изменить существующий элемент в базе данных"))
        self.newButton.setText(_translate("Form", "Добавить новый элемент"))
